import {
  DEMO_ARTIST_NAME,
  DEMO_CAMPAIGN_NAME,
  DEMO_DATA_MARKER,
  DEMO_IDS,
  DEMO_SONG_TITLE,
  demoDates,
} from "@/lib/demo-data/constants"
import type { ExternalLinkRecord } from "@/lib/types"

export function buildPrettyWiseDemoExternalLinks(): ExternalLinkRecord[] {
  const { timestamp: ts } = demoDates()

  return [
    {
      id: DEMO_IDS.extLinkYoutube,
      name: "PrettyWise Cotton Candy Skies YouTube Video",
      platform: "YouTube",
      linkType: "Published Video",
      url: "https://youtube.com/watch?v=demo-cotton-candy-skies",
      status: "Active",
      campaignId: DEMO_IDS.campaign,
      campaignName: DEMO_CAMPAIGN_NAME,
      artistName: DEMO_ARTIST_NAME,
      songTitle: DEMO_SONG_TITLE,
      productName: "",
      sourceRecordType: "youtube-package",
      sourceRecordId: DEMO_IDS.youtubePackage,
      assetId: "",
      analyticsRecordId: DEMO_IDS.analytics,
      notes: DEMO_DATA_MARKER,
      tags: ["prettywise", "demo", "youtube"],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: DEMO_IDS.extLinkDrive,
      name: "PrettyWise Google Drive Campaign Folder",
      platform: "Google Drive",
      linkType: "Google Drive Folder",
      url: "https://drive.google.com/drive/folders/demo-prettywise-cotton-candy-skies",
      status: "Active",
      campaignId: DEMO_IDS.campaign,
      campaignName: DEMO_CAMPAIGN_NAME,
      artistName: DEMO_ARTIST_NAME,
      songTitle: DEMO_SONG_TITLE,
      productName: "",
      sourceRecordType: "",
      sourceRecordId: "",
      assetId: "",
      analyticsRecordId: "",
      notes: DEMO_DATA_MARKER,
      tags: ["prettywise", "demo", "google-drive"],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: DEMO_IDS.extLinkSuno,
      name: "PrettyWise Suno Project",
      platform: "Suno",
      linkType: "Suno Project",
      url: "https://suno.com/song/demo-prettywise-cotton-candy-skies",
      status: "Active",
      campaignId: DEMO_IDS.campaign,
      campaignName: DEMO_CAMPAIGN_NAME,
      artistName: DEMO_ARTIST_NAME,
      songTitle: DEMO_SONG_TITLE,
      productName: "",
      sourceRecordType: "release-plan",
      sourceRecordId: DEMO_IDS.releasePlan,
      assetId: "",
      analyticsRecordId: "",
      notes: DEMO_DATA_MARKER,
      tags: ["prettywise", "demo", "suno"],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: DEMO_IDS.extLinkFourthwall,
      name: "PrettyWise Fourthwall Shirt",
      platform: "Fourthwall",
      linkType: "Fourthwall Product",
      url: "https://example.com/fourthwall/prettywise-cotton-candy-skies-shirt",
      status: "Active",
      campaignId: DEMO_IDS.campaign,
      campaignName: DEMO_CAMPAIGN_NAME,
      artistName: DEMO_ARTIST_NAME,
      songTitle: DEMO_SONG_TITLE,
      productName: "Cotton Candy Skies Shirt",
      sourceRecordType: "product-listing",
      sourceRecordId: DEMO_IDS.productListing,
      assetId: "",
      analyticsRecordId: "",
      notes: DEMO_DATA_MARKER,
      tags: ["prettywise", "demo", "fourthwall"],
      createdAt: ts,
      updatedAt: ts,
    },
  ]
}
