import type { Prompt, Workflow } from "./types"

export const SEED_PROMPTS: Prompt[] = [
  {
    id: "p-yt-title",
    name: "YouTube Title Generator",
    category: "YouTube",
    description:
      "Generates click-worthy but honest titles for AI music videos based on mood and genre.",
    promptText:
      "You are a YouTube growth strategist for an AI music channel. Generate 10 title options for a video.\n\nGenre: {{genre}}\nMood: {{mood}}\nTrack name: {{trackName}}\n\nRules:\n- Keep under 60 characters\n- No clickbait that misrepresents the track\n- Include the mood or use case (study, sleep, focus, etc.)\nReturn a numbered list.",
    variables: ["genre", "mood", "trackName"],
    outputFormat: "Numbered list (10 items)",
    tags: ["titles", "growth", "seo"],
    rating: 5,
    notes: "Works best when you give a specific use case in the mood field.",
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "p-music-desc",
    name: "Track Description Writer",
    category: "Music",
    description:
      "Writes streaming platform descriptions and metadata for AI-generated tracks.",
    promptText:
      "Write a 2-sentence description for a track.\n\nTitle: {{title}}\nGenre: {{genre}}\nBPM: {{bpm}}\nMood tags: {{moodTags}}\n\nThen list 8 relevant Spotify-style mood/activity tags.",
    variables: ["title", "genre", "bpm", "moodTags"],
    outputFormat: "Paragraph + tag list",
    tags: ["metadata", "spotify", "distribution"],
    rating: 4,
    notes: "",
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: "p-art-cover",
    name: "Album Cover Art Prompt",
    category: "Artwork",
    description:
      "Builds detailed image-model prompts for cohesive album / single cover art.",
    promptText:
      "Create an image generation prompt for album cover art.\n\nVibe: {{vibe}}\nColor palette: {{palette}}\nSubject: {{subject}}\n\nOutput a single richly detailed prompt under 80 words, plus a negative prompt line.",
    variables: ["vibe", "palette", "subject"],
    outputFormat: "Prompt + negative prompt",
    tags: ["midjourney", "cover-art", "branding"],
    rating: 5,
    notes: "Pair with the brand palette for consistency across releases.",
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now() - 86400000 * 6,
  },
  {
    id: "p-merch-copy",
    name: "Merch Product Copy",
    category: "Merch",
    description: "Generates product titles and descriptions for merch listings.",
    promptText:
      "Write an ecommerce product title and 3-bullet description.\n\nProduct: {{product}}\nDesign theme: {{theme}}\nAudience: {{audience}}\n\nKeep it punchy and benefit-driven.",
    variables: ["product", "theme", "audience"],
    outputFormat: "Title + 3 bullets",
    tags: ["ecommerce", "copywriting"],
    rating: 3,
    notes: "",
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-merch-idea",
    name: "Merch Idea Generator",
    category: "Merch",
    description:
      "Generates merch concept names, slogans, design directions, and listing copy for niche products.",
    promptText:
      "You are a merch and ecommerce product strategist for creators, artists, and niche brands.\n\nGenerate creative merch product concepts based on the following:\n\nNiche: {{niche}}\nAudience: {{audience}}\nProduct type: {{productType}}\nTone: {{tone}}\nNoun: {{noun}}\nVerb: {{verb}}\nDesign style: {{designStyle}}\nStore type: {{storeType}}\nPrimary goal: {{primaryGoal}}\n\nAdditional notes: {{notes}}\n\nGenerate:\n1. Five distinct merch concept names\n2. A catchy slogan for each concept\n3. Design direction notes (colors, typography, imagery)\n4. Product title and description for the store listing\n5. Relevant tags for search and discovery\n6. Mockup ideas for product photography or mockups\n7. A social media caption to promote the product\n\nMake concepts specific to the niche and audience. Vary humor level based on tone.",
    variables: [
      "niche",
      "audience",
      "productType",
      "tone",
      "noun",
      "verb",
      "designStyle",
      "storeType",
      "primaryGoal",
      "notes",
    ],
    outputFormat:
      "Concept names, slogans, design directions, listing copy, tags, mockup ideas, and social captions",
    tags: ["merch", "ecommerce", "fourthwall", "product-ideas"],
    rating: 5,
    notes: "Use for artist merch, funny shirts, niche products, and digital goods.",
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-product-listing",
    name: "Product Listing Generator",
    category: "Merch",
    description:
      "Generates ecommerce product titles, descriptions, tags, and promo copy for merch and digital products.",
    promptText:
      "You are an ecommerce copywriter and product listing strategist for creators, artists, and digital product sellers.\n\nGenerate a complete product listing based on the following:\n\nProduct type: {{productType}}\nNiche: {{niche}}\nAudience: {{audience}}\nDesign concept: {{designConcept}}\nTone: {{tone}}\nPrimary keyword: {{primaryKeyword}}\nSecondary keywords: {{secondaryKeywords}}\nStore name: {{storeName}}\nProduct benefits: {{productBenefits}}\nPricing notes: {{pricingNotes}}\n\nAdditional notes: {{notes}}\n\nGenerate:\n1. Three product title options optimized for search and conversion\n2. A short description (1-2 sentences) for listing previews\n3. A long description (2-3 paragraphs) with benefits and use cases\n4. Five bullet points highlighting key features and benefits\n5. 10-15 relevant tags for search and discovery\n6. A suggested collection or category name\n7. A compelling call-to-action line\n8. A social media caption to promote the product\n9. An email subject line for a product launch announcement\n\nMatch tone to the audience. Optimize for the store platform when relevant.",
    variables: [
      "productType",
      "niche",
      "audience",
      "designConcept",
      "tone",
      "primaryKeyword",
      "secondaryKeywords",
      "storeName",
      "productBenefits",
      "pricingNotes",
      "notes",
    ],
    outputFormat:
      "Titles, descriptions, bullet points, tags, collection, CTA, social caption, and email subject",
    tags: ["ecommerce", "product-listing", "copywriting", "seo"],
    rating: 5,
    notes:
      "Use for merch, digital products, templates, prompt packs, and tech resources.",
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-social-repurposing",
    name: "Social Repurposing Engine",
    category: "Marketing",
    description:
      "Repurposes one source idea into platform-specific content for TikTok, Instagram, X, YouTube, and email.",
    promptText:
      "You are a social media content strategist who repurposes one source idea into platform-specific content.\n\nTurn the following source into tailored content for TikTok, Instagram, X, YouTube Shorts, YouTube Community, and email.\n\nCampaign name: {{campaignName}}\nSource content: {{sourceContent}}\nBusiness area: {{businessArea}}\nContent type: {{contentType}}\nGoal: {{goal}}\nAudience: {{audience}}\nTone: {{tone}}\nPlatforms: {{platforms}}\nCall to action: {{callToAction}}\nProduct or release link: {{productOrReleaseLink}}\n\nAdditional notes: {{notes}}\n\nGenerate:\n1. A core message that anchors all platform versions\n2. A TikTok caption optimized for short-form video\n3. An Instagram caption with line breaks and engagement hooks\n4. An X post under 280 characters (or a thread opener if needed)\n5. A YouTube Shorts concept or hook idea\n6. A YouTube Community post draft\n7. A short email snippet for a newsletter or announcement\n8. Relevant hashtags grouped by platform where appropriate\n9. A final CTA line tailored to the goal\n\nMatch tone and format to each platform. Keep the core message consistent across channels.",
    variables: [
      "campaignName",
      "sourceContent",
      "businessArea",
      "contentType",
      "goal",
      "audience",
      "tone",
      "platforms",
      "callToAction",
      "productOrReleaseLink",
      "notes",
    ],
    outputFormat:
      "Core message, TikTok, Instagram, X, YouTube Shorts, Community post, email snippet, hashtags, and CTA",
    tags: ["social", "repurposing", "tiktok", "instagram", "youtube"],
    rating: 5,
    notes:
      "Use to turn one release, product, or announcement into multi-platform content.",
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-release-planner",
    name: "AI Music Release Planner",
    category: "Music",
    description:
      "Creates comprehensive release plans for AI music across YouTube, streaming, social, email, and merch.",
    promptText:
      "You are a music release strategist for AI-generated music artists and independent labels.\n\nCreate a comprehensive release plan for the following track:\n\nArtist: {{artistName}}\nSong title: {{songTitle}}\nGenre: {{genre}}\nMood: {{mood}}\nRelease date: {{releaseDate}}\nYouTube channel: {{youtubeChannel}}\nTarget audience: {{targetAudience}}\nVisual theme: {{visualTheme}}\nMerch tie-in: {{merchTieIn}}\nStreaming platforms: {{streamingPlatforms}}\nPrimary goal: {{primaryGoal}}\n\nAdditional notes: {{notes}}\n\nGenerate:\n1. A strategy summary aligned to the primary goal\n2. A target listener profile\n3. A 14-day pre-release plan with daily or grouped tasks\n4. A release day checklist\n5. A 7-day post-release plan\n6. YouTube packaging recommendations (title, description, tags, community post ideas)\n7. Short-form content ideas for TikTok, Reels, and Shorts\n8. Social captions for key platforms\n9. An email announcement draft\n10. Merch tie-in ideas if applicable\n11. Priority tasks ranked by impact\n12. A master final checklist\n\nBe specific to the genre, mood, and audience. Include actionable tasks across YouTube, streaming, social, email, and merch.",
    variables: [
      "artistName",
      "songTitle",
      "genre",
      "mood",
      "releaseDate",
      "youtubeChannel",
      "targetAudience",
      "visualTheme",
      "merchTieIn",
      "streamingPlatforms",
      "primaryGoal",
      "notes",
    ],
    outputFormat:
      "Strategy, pre/post-release plans, YouTube package, social content, email, merch tie-ins, and checklists",
    tags: ["music", "release", "planning", "youtube", "streaming"],
    rating: 5,
    notes:
      "Use for full AI music release planning from pre-launch through post-release tracking.",
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-mockup-prompt",
    name: "Mockup Prompt Generator",
    category: "Artwork",
    description:
      "Generates image and mockup prompts for merch, thumbnails, product ads, and ecommerce visuals.",
    promptText:
      "You are an expert image prompt engineer for merch mockups, digital products, artist visuals, YouTube thumbnails, product ads, and ecommerce creatives.\n\nCreate image generation prompts based on the following project details:\n\nProject name: {{projectName}}\nMockup type: {{mockupType}}\nProduct type: {{productType}}\nNiche: {{niche}}\nAudience: {{audience}}\nDesign concept: {{designConcept}}\nVisual style: {{visualStyle}}\nColors: {{colors}}\nSetting: {{setting}}\nModel description: {{modelDescription}}\nCamera angle: {{cameraAngle}}\nLighting: {{lighting}}\nMood: {{mood}}\nPlatform use: {{platformUse}}\nAspect ratio: {{aspectRatio}}\nText to include: {{textToInclude}}\nText to avoid: {{textToAvoid}}\nBrand notes: {{brandNotes}}\n\nAdditional notes: {{notes}}\n\nGenerate:\n1. One polished, detailed image generation prompt ready for Midjourney, DALL-E, or similar\n2. One simpler, shorter prompt version\n3. One premium ecommerce version optimized for product listings\n4. One social media ad version optimized for the target platform\n5. A negative prompt / avoid list\n6. Layout notes (composition, framing, focal points)\n7. Text placement notes (where text should appear, size, hierarchy)\n8. Mockup usage recommendations (which version to use where)\n\nMatch visual style and mood to the niche and audience. Respect aspect ratio and platform constraints.",
    variables: [
      "projectName",
      "mockupType",
      "productType",
      "niche",
      "audience",
      "designConcept",
      "visualStyle",
      "colors",
      "setting",
      "modelDescription",
      "cameraAngle",
      "lighting",
      "mood",
      "platformUse",
      "aspectRatio",
      "textToInclude",
      "textToAvoid",
      "brandNotes",
      "notes",
    ],
    outputFormat:
      "Polished prompt, simple prompt, ecommerce version, social ad version, negative prompt, layout, text placement, and usage notes",
    tags: ["mockup", "image-prompt", "midjourney", "ecommerce", "thumbnail"],
    rating: 5,
    notes:
      "Use for merch mockups, YouTube thumbnails, product ads, and social creatives.",
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-email-campaign",
    name: "Email Campaign Generator",
    category: "Marketing",
    description:
      "Generates subject lines, preview text, email bodies, follow-ups, and resend versions for creator campaigns.",
    promptText:
      "You are an expert email marketing strategist for music releases, merch drops, digital products, courses, and creator brands.\n\nCreate a complete email campaign based on the following:\n\nCampaign name: {{campaignName}}\nCampaign type: {{campaignType}}\nBusiness area: {{businessArea}}\nAudience: {{audience}}\nOffer or announcement: {{offerOrAnnouncement}}\nProduct or release name: {{productOrReleaseName}}\nKey benefits: {{keyBenefits}}\nTone: {{tone}}\nCall to action: {{callToAction}}\nLink: {{link}}\nUrgency: {{urgency}}\nSender name: {{senderName}}\n\nAdditional notes: {{notes}}\n\nGenerate:\n1. 10 subject line options\n2. 10 preview text options\n3. Three email body versions (standard, short, and story-driven)\n4. One short version optimized for mobile skimmers\n5. One story-driven version with narrative hook\n6. One direct sales version focused on conversion\n7. CTA options (button text and supporting lines)\n8. A follow-up email for non-clickers\n9. A resend version for non-openers (new subject + shorter body)\n10. Segmentation ideas for who should receive which version\n\nMatch tone to the audience and business area. Keep subject lines under 60 characters when possible.",
    variables: [
      "campaignName",
      "campaignType",
      "businessArea",
      "audience",
      "offerOrAnnouncement",
      "productOrReleaseName",
      "keyBenefits",
      "tone",
      "callToAction",
      "link",
      "urgency",
      "senderName",
      "notes",
    ],
    outputFormat:
      "Subject lines, preview text, email bodies, CTAs, follow-up, resend, and segmentation ideas",
    tags: ["email", "marketing", "newsletter", "launch", "campaign"],
    rating: 5,
    notes:
      "Use for music releases, merch drops, product launches, and newsletter campaigns.",
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-youtube-thumbnail",
    name: "YouTube Thumbnail Generator",
    category: "YouTube",
    description:
      "Generates thumbnail concepts, text hooks, composition guidance, and image prompts for videos and Shorts.",
    promptText:
      "You are an expert YouTube thumbnail strategist for music channels, AI artists, and creator brands.\n\nCreate a complete thumbnail strategy and concepts based on the following:\n\nTrack title: {{trackTitle}}\nArtist: {{artistName}}\nVideo title: {{videoTitle}}\nContent format: {{contentFormat}}\nVideo type: {{videoType}}\nGenre: {{genre}}\nMood: {{mood}}\nTarget audience: {{targetAudience}}\nVisual theme: {{visualTheme}}\nHook angle: {{hookAngle}}\nMain subject: {{mainSubject}}\nText overlay: {{textOverlay}}\nColor direction: {{colorDirection}}\nBranding notes: {{brandingNotes}}\nReference style: {{referenceStyle}}\nCTA goal: {{ctaGoal}}\n\nAdditional notes: {{notes}}\n\nGenerate:\n1. A thumbnail strategy summary aligned to the CTA goal and content format\n2. 10 distinct thumbnail concepts with brief descriptions\n3. 10 text hook options for overlay text (keep under 4 words when possible)\n4. Best angle recommendation (camera angle, subject placement, focal point)\n5. Emotional trigger recommendation for the target audience\n6. Composition guidance (rule of thirds, negative space, contrast zones)\n7. Color guidance (palette, contrast, accent colors for readability)\n8. Three A/B test variations to compare click performance\n9. One final, detailed image generation prompt ready for Midjourney, DALL-E, or similar\n10. One Shorts cover variation if content format is YouTube Shorts Cover or if a vertical crop is useful\n11. Do and don't recommendations for this niche and format\n\nOptimize for mobile readability at small sizes. Ensure text overlay suggestions remain legible on YouTube's thumbnail grid.",
    variables: [
      "trackTitle",
      "artistName",
      "videoTitle",
      "contentFormat",
      "videoType",
      "genre",
      "mood",
      "targetAudience",
      "visualTheme",
      "hookAngle",
      "mainSubject",
      "textOverlay",
      "colorDirection",
      "brandingNotes",
      "referenceStyle",
      "ctaGoal",
      "notes",
    ],
    outputFormat:
      "Strategy, concepts, hooks, composition, color guidance, A/B tests, image prompt, Shorts variation, do/don't",
    tags: ["youtube", "thumbnail", "shorts", "music", "visual"],
    rating: 5,
    notes:
      "Use for standard video thumbnails and YouTube Shorts covers for music and creator content.",
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-mkt-thread",
    name: "Release Announcement Thread",
    category: "Marketing",
    description: "Drafts a social thread to announce a new release across platforms.",
    promptText:
      "Write a 5-post launch thread announcing a new release.\n\nRelease: {{release}}\nPlatform: {{platform}}\nLink: {{link}}\n\nPost 1 hooks, posts 2-4 build, post 5 has the CTA.",
    variables: ["release", "platform", "link"],
    outputFormat: "5 numbered posts",
    tags: ["social", "launch", "twitter"],
    rating: 4,
    notes: "",
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
  },
  {
    id: "p-label-brief",
    name: "Artist Onboarding Brief",
    category: "Label Ops",
    description:
      "Creates a structured onboarding brief when signing a new artist to the label.",
    promptText:
      "Generate an artist onboarding checklist and welcome brief.\n\nArtist: {{artist}}\nGenre: {{genre}}\nDeliverables: {{deliverables}}\n\nInclude sections: assets needed, timeline, points of contact.",
    variables: ["artist", "genre", "deliverables"],
    outputFormat: "Structured brief with sections",
    tags: ["operations", "onboarding"],
    rating: 4,
    notes: "Reuse for every new signing.",
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 10,
  },
  {
    id: "p-yt-metadata",
    name: "YouTube Metadata Generator",
    category: "YouTube",
    description:
      "Generates YouTube titles, descriptions, tags, and promotion copy for AI music releases.",
    promptText:
      "You are a YouTube metadata strategist for an AI music channel.\n\nTrack: {{trackTitle}}\nArtist: {{artistName}}\nGenre: {{genre}}\nMood: {{mood}}\nTarget listener: {{targetListener}}\nVisual theme: {{visualTheme}}\nPrimary goal: {{primaryGoal}}\nMerch tie-in: {{merchTieIn}}\nStreaming link: {{streamingLink}}\n\nGenerate:\n1. Three title options under 60 characters\n2. A keyword-rich description (2 short paragraphs)\n3. 15 relevant tags\n4. One pinned comment draft\n5. Three community post ideas to promote the release",
    variables: [
      "trackTitle",
      "artistName",
      "genre",
      "mood",
      "targetListener",
      "visualTheme",
      "primaryGoal",
      "merchTieIn",
      "streamingLink",
    ],
    outputFormat: "Structured sections with titles, description, tags, and promo copy",
    tags: ["youtube", "metadata", "seo", "release"],
    rating: 5,
    notes: "Use for full release metadata packs before upload.",
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 1,
  },
]

export const SEED_WORKFLOWS: Workflow[] = [
  {
    id: "w-release",
    name: "Full Release Pipeline",
    category: "Music",
    description:
      "End-to-end flow from finished track to published, promoted release.",
    status: "Active",
    estimatedTimeSaved: "4h / release",
    steps: [
      {
        id: "s1",
        title: "Write track metadata",
        description: "Generate description and tags for distribution.",
        promptId: "p-music-desc",
      },
      {
        id: "s2",
        title: "Generate cover art",
        description: "Build the image prompt and render covers.",
        promptId: "p-art-cover",
      },
      {
        id: "s3",
        title: "Create YouTube title",
        description: "Pick the best performing title option.",
        promptId: "p-yt-title",
      },
      {
        id: "s4",
        title: "Announce release",
        description: "Draft the launch thread for socials.",
        promptId: "p-mkt-thread",
      },
    ],
    notes: "Run this for every single and album drop.",
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "w-merch",
    name: "Merch Drop Setup",
    category: "Merch",
    description: "Prepare listings and promo for a new merch drop.",
    status: "Active",
    estimatedTimeSaved: "2h / drop",
    steps: [
      {
        id: "s1",
        title: "Write product copy",
        description: "Generate titles and descriptions for each item.",
        promptId: "p-merch-copy",
      },
      {
        id: "s2",
        title: "Promo thread",
        description: "Announce the drop on social.",
        promptId: "p-mkt-thread",
      },
    ],
    notes: "",
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: "w-yt-upload",
    name: "YouTube Music Upload Workflow",
    category: "YouTube",
    description:
      "Upload-ready metadata and promotion copy for a new AI music video release.",
    status: "Active",
    estimatedTimeSaved: "3h / upload",
    steps: [
      {
        id: "yt-s1",
        title: "Generate YouTube metadata",
        description: "Titles, description, tags, and pinned comment.",
        promptId: "p-yt-metadata",
      },
      {
        id: "yt-s2",
        title: "Pick the best title",
        description: "Choose and refine the top title option.",
        promptId: "p-yt-title",
      },
      {
        id: "yt-s3",
        title: "Announce the upload",
        description: "Draft the launch thread for socials.",
        promptId: "p-mkt-thread",
      },
    ],
    notes: "Run before every YouTube music upload.",
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "w-release-campaign",
    name: "AI Music Release Campaign Workflow",
    category: "Marketing",
    description:
      "Full release campaign from track metadata to social announcement.",
    status: "Active",
    estimatedTimeSaved: "5h / release",
    steps: [
      {
        id: "rc-s1",
        title: "Write track metadata",
        description: "Streaming description and mood tags.",
        promptId: "p-music-desc",
      },
      {
        id: "rc-s2",
        title: "Generate cover art prompt",
        description: "Build the visual direction for cover art.",
        promptId: "p-art-cover",
      },
      {
        id: "rc-s3",
        title: "Create YouTube metadata",
        description: "Full YouTube upload metadata pack.",
        promptId: "p-yt-metadata",
      },
      {
        id: "rc-s4",
        title: "Launch announcement",
        description: "Social thread and promo copy.",
        promptId: "p-mkt-thread",
      },
    ],
    notes: "End-to-end campaign for singles and EPs.",
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "w-merch-launch",
    name: "Merch Product Launch Workflow",
    category: "Merch",
    description: "Product copy, listings, and launch promo for a merch drop.",
    status: "Active",
    estimatedTimeSaved: "2.5h / drop",
    steps: [
      {
        id: "ml-s1",
        title: "Write product copy",
        description: "Titles and descriptions for each product.",
        promptId: "p-merch-copy",
      },
      {
        id: "ml-s2",
        title: "Plan launch promo",
        description: "Social thread announcing the merch drop.",
        promptId: "p-mkt-thread",
      },
    ],
    notes: "Use for every new merch product or collection.",
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: "w-signing",
    name: "New Artist Signing",
    category: "Label Ops",
    description: "Standard onboarding when bringing a new artist onto the label.",
    status: "Draft",
    estimatedTimeSaved: "3h / artist",
    steps: [
      {
        id: "s1",
        title: "Build onboarding brief",
        description: "Generate the welcome brief and checklist.",
        promptId: "p-label-brief",
      },
    ],
    notes: "Still refining the contract step.",
    createdAt: Date.now() - 86400000 * 18,
    updatedAt: Date.now() - 86400000 * 8,
  },
]
