import type { PresetType } from "@/lib/types"

export interface StarterPresetDefinition {
  starterId: string
  name: string
  description: string
  presetType: PresetType
  category: string
  tags: string[]
  values: Record<string, unknown>
  notes: string
}

export const STARTER_PRESETS: StarterPresetDefinition[] = [
  {
    starterId: "starter-dark-ai-music-release",
    name: "Dark AI Music Release",
    description:
      "Launch plan for a dark electronic AI music single with streaming and YouTube focus.",
    presetType: "Campaign",
    category: "Music Release",
    tags: ["dark", "ai-music", "release"],
    values: {
      campaignName: "Dark AI Music Release",
      campaignType: "Music Release",
      status: "Planning",
      priority: "High",
      artistName: "Neon Atlas",
      songTitle: "Midnight Circuit",
      niche: "Dark AI Music",
      primaryGoal: "Drive streams, YouTube views, and playlist adds",
      targetAudience: "Late-night electronic and synthwave listeners",
      launchDate: "2026-07-15",
      description:
        "Coordinate release assets across YouTube, streaming, social, and email.",
    },
    notes: "Starter campaign for dark electronic AI releases.",
  },
  {
    starterId: "starter-cyberpunk-youtube-video",
    name: "Cyberpunk YouTube Video",
    description:
      "YouTube packaging preset for a cinematic cyberpunk visualizer or music video.",
    presetType: "YouTube Package",
    category: "YouTube",
    tags: ["cyberpunk", "youtube", "visualizer"],
    values: {
      trackTitle: "Midnight Circuit",
      artistName: "Neon Atlas",
      channelName: "Neon Atlas Official",
      genre: "Cyberpunk Electronic",
      mood: "Dark, cinematic, futuristic",
      targetListener: "Synthwave and cyberpunk fans",
      visualTheme: "Neon city, rain, holograms, chrome reflections",
      primaryGoal: "Views",
      videoType: "Visualizer",
      keywords: "cyberpunk music, dark electronic, ai artist, neon synth",
      notes: "Optimize title and description for search and suggested traffic.",
    },
    notes: "Pair with the YouTube Thumbnail preset for a full upload package.",
  },
  {
    starterId: "starter-horror-kpop-release",
    name: "Horror K-Pop Release",
    description: "Release plan for a horror-concept K-pop inspired track rollout.",
    presetType: "Release Plan",
    category: "Music Release",
    tags: ["k-pop", "horror", "release-plan"],
    values: {
      artistName: "VELA",
      songTitle: "Crimson Mirror",
      genre: "K-Pop / Dark Pop",
      mood: "Haunting, dramatic, cinematic",
      releaseDate: "2026-08-01",
      youtubeChannel: "VELA Official",
      targetAudience: "K-pop and dark pop fans",
      visualTheme: "Gothic glamour, mirror motifs, red and black palette",
      primaryGoal: "Build pre-save momentum and release day streams",
      notes: "Lean into teaser clips, concept photos, and countdown content.",
    },
    notes: "Use for pre-release planning and day-of checklist.",
  },
  {
    starterId: "starter-merch-drop",
    name: "Merch Drop",
    description: "Campaign template for a limited merch drop tied to a release.",
    presetType: "Campaign",
    category: "Merch",
    tags: ["merch", "drop", "campaign"],
    values: {
      campaignName: "Limited Merch Drop",
      campaignType: "Merch Drop",
      status: "Planning",
      priority: "High",
      artistName: "Neon Atlas",
      productName: "Midnight Circuit Tee",
      niche: "Dark AI Music Merch",
      primaryGoal: "Sell through limited drop and social urgency",
      targetAudience: "Superfans and electronic music collectors",
      launchDate: "2026-07-22",
      description: "Coordinate mockups, listings, email, and social promo.",
    },
    notes: "Link merch ideas and product listings after install.",
  },
  {
    starterId: "starter-funny-shirt-product-launch",
    name: "Funny Shirt Product Launch",
    description: "Product listing preset for a humorous creator-focused shirt.",
    presetType: "Product Listing",
    category: "Commerce",
    tags: ["funny", "shirt", "product"],
    values: {
      productType: "T-shirt",
      niche: "AI Music Creators",
      audience: "Independent musicians and AI artists",
      designConcept: "Funny slogan about prompts, algorithms, and 3am releases",
      tone: "Playful, witty, relatable",
      primaryKeyword: "funny music producer shirt",
      secondaryKeywords: "ai music, creator merch, studio humor",
      storeName: "CreatorOps Merch",
      productBenefits: "Soft cotton, unisex fit, conversation starter",
      pricingNotes: "Premium tee at $28–32",
    },
    notes: "Pair with a mockup prompt preset for product images.",
  },
  {
    starterId: "starter-digital-product-launch",
    name: "Digital Product Launch",
    description: "Campaign for launching a digital download or template pack.",
    presetType: "Campaign",
    category: "Digital Product",
    tags: ["digital", "launch", "product"],
    values: {
      campaignName: "Digital Product Launch",
      campaignType: "Digital Product Launch",
      status: "Planning",
      priority: "Medium",
      productName: "Creator Launch Kit",
      niche: "Creator Tools",
      primaryGoal: "Drive product page visits and first-week sales",
      targetAudience: "Independent creators and musicians",
      launchDate: "2026-09-01",
      description: "Launch landing page, email sequence, and social proof assets.",
    },
    notes: "Use analytics records to track conversion after launch.",
  },
  {
    starterId: "starter-prompt-pack-launch",
    name: "Prompt Pack Launch",
    description: "Campaign for releasing a curated prompt pack or workflow bundle.",
    presetType: "Campaign",
    category: "Prompts",
    tags: ["prompts", "pack", "launch"],
    values: {
      campaignName: "Prompt Pack Launch",
      campaignType: "Content Campaign",
      status: "Planning",
      priority: "Medium",
      productName: "Release Week Prompt Pack",
      niche: "AI Creator Prompts",
      primaryGoal: "Sell prompt pack and grow email list",
      targetAudience: "AI musicians and content repurposers",
      launchDate: "2026-08-15",
      description: "Bundle prompts for titles, captions, thumbnails, and emails.",
    },
    notes: "Cross-link saved prompts and workflows in Campaign Builder.",
  },
  {
    starterId: "starter-mini-course-launch",
    name: "Mini Course Launch",
    description: "Campaign for a short educational mini course or workshop.",
    presetType: "Campaign",
    category: "Education",
    tags: ["course", "launch", "education"],
    values: {
      campaignName: "Mini Course Launch",
      campaignType: "Product Launch",
      status: "Planning",
      priority: "High",
      productName: "Release Strategy Mini Course",
      niche: "Music Marketing Education",
      primaryGoal: "Fill cohort and drive enrollments",
      targetAudience: "Independent AI artists learning release strategy",
      launchDate: "2026-10-01",
      description: "Webinar, email nurture, testimonials, and checkout funnel.",
    },
    notes: "Add email campaign and social repurposing presets for nurture content.",
  },
  {
    starterId: "starter-tech-template-launch",
    name: "Tech Template Launch",
    description: "Product listing for a Notion/Figma/Canva-style creator template.",
    presetType: "Product Listing",
    category: "Digital Product",
    tags: ["template", "tech", "digital"],
    values: {
      productType: "Digital Download",
      niche: "Creator Operations",
      audience: "Solo creators and small labels",
      designConcept: "Release planning template with campaign tracker",
      tone: "Professional, clean, practical",
      primaryKeyword: "music release template",
      secondaryKeywords: "creator ops, release planner, campaign tracker",
      storeName: "CreatorOps Digital",
      productBenefits: "Editable template, instant download, reusable each release",
      pricingNotes: "One-time purchase at $19–29",
    },
    notes: "Good for Gumroad, Fourthwall, or Etsy digital listings.",
  },
  {
    starterId: "starter-artist-branding-campaign",
    name: "Artist Branding Campaign",
    description: "Campaign to establish visual identity and audience positioning.",
    presetType: "Campaign",
    category: "Branding",
    tags: ["branding", "artist", "identity"],
    values: {
      campaignName: "Artist Branding Campaign",
      campaignType: "Artist Campaign",
      status: "Planning",
      priority: "Medium",
      artistName: "Neon Atlas",
      niche: "Dark AI Music",
      primaryGoal: "Clarify brand story and visual identity across channels",
      targetAudience: "Electronic music fans discovering the artist",
      launchDate: "2026-06-15",
      description:
        "Define palette, typography, bio, content pillars, and channel consistency.",
    },
    notes: "Link artist CRM, thumbnails, and social content as assets are created.",
  },
]
