"use server"

import { revalidatePath } from "next/cache"

import { saveLinkedPromptRun } from "@/lib/actions/linked-prompt-runs"
import { getWorkspaceSettings } from "@/lib/actions/workspace-settings"
import {
  generateAITextWithProvider,
  resolveProviderStatus,
} from "@/lib/ai/ai-client"
import { assembleAIPrompt, mergePromptForPreview } from "@/lib/ai/prompt-assembler"
import type {
  AIProviderId,
  AIProviderStatus,
  GenerateAITextInput,
  GenerateAITextResult,
} from "@/lib/ai/types"
import type { CampaignLinkedRecordType, PromptRunModuleType } from "@/lib/types"

const REVALIDATE_PATHS = ["/runner", "/campaigns", "/settings", "/activity", "/backups"]

function revalidateAIRoutes() {
  for (const path of REVALIDATE_PATHS) {
    revalidatePath(path)
  }
}

function safeErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message
  return "AI generation failed."
}

/** Non-secret provider readiness for client UI. */
export async function getAIProviderStatus(): Promise<AIProviderStatus> {
  try {
    const settings = await getWorkspaceSettings()
    return resolveProviderStatus({
      enabled: settings.aiGenerationEnabled,
      preferredProvider: settings.aiDefaultProvider,
      preferredModel: settings.aiDefaultModel,
    })
  } catch {
    return resolveProviderStatus({
      enabled: false,
      preferredProvider: "openai",
      preferredModel: "",
    })
  }
}

/** Server-side text generation with optional PromptRun persistence. */
export async function generateAIText(
  input: GenerateAITextInput,
): Promise<GenerateAITextResult> {
  try {
    const settings = await getWorkspaceSettings()
    const status = resolveProviderStatus({
      enabled: settings.aiGenerationEnabled,
      preferredProvider: input.provider ?? settings.aiDefaultProvider,
      preferredModel: input.model ?? settings.aiDefaultModel,
    })

    if (!settings.aiGenerationEnabled) {
      return {
        success: false,
        error: "AI generation is disabled. Enable it in Settings → AI Providers.",
      }
    }

    if (!status.configured || status.provider === "manual") {
      return {
        success: false,
        error:
          status.setupMessage ??
          "AI provider not configured. Add OPENAI_API_KEY to .env.local.",
      }
    }

    const assembled = await assembleAIPrompt(input)
    const provider = (input.provider?.trim() || status.provider) as AIProviderId
    const model = input.model?.trim() || status.model
    const temperature = input.temperature ?? settings.aiTemperature
    const maxTokens = input.maxTokens ?? settings.aiMaxOutputTokens

    const result = await generateAITextWithProvider(provider, {
      provider,
      model,
      systemPrompt: assembled.systemPrompt,
      userPrompt: assembled.userPrompt,
      temperature,
      maxTokens,
    })

    const shouldSave =
      input.savePromptRun ?? settings.aiSaveGenerationsAsPromptRuns
    let promptRunId: string | undefined

    if (shouldSave && (input.promptText.trim() || result.text.trim())) {
      const saved = await saveLinkedPromptRun({
        completedPrompt: input.promptText.trim() || assembled.userPrompt,
        aiResponse: result.text,
        inputValues: input.inputValues,
        promptId: input.promptId,
        promptName: input.promptName ?? `${input.moduleType} AI generation`,
        moduleType: input.moduleType as PromptRunModuleType,
        campaignId: input.campaignId,
        outputRecordId: input.outputRecordId,
        outputRecordType: input.outputRecordType as CampaignLinkedRecordType | undefined,
        experimentId: input.experimentId,
        notes: input.notes ?? "Generated by CreatorOps AI",
        tags: ["ai-generated"],
        runType: "ai-generation",
      })
      promptRunId = saved.id
      revalidateAIRoutes()
    }

    return {
      success: true,
      text: result.text,
      provider: result.provider,
      model: result.model,
      promptRunId,
      assembledPrompt: mergePromptForPreview(assembled),
      systemPrompt: assembled.systemPrompt,
    }
  } catch (error) {
    return { success: false, error: safeErrorMessage(error) }
  }
}
